# Generated by Django 3.0.5 on 2020-06-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authuser',
            new_name='user',
        ),
    ]
